import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const BUCKET="patrimonio-fotos",MAX_BATCH=25,MAX_ATTEMPTS=8;
type O={id:number;patrimonio_id:number;foto_id:number;evento:string;status:string;tentativas:number;proxima_tentativa_em:string|null};
type F={id:number;patrimonio_id:number;storage_bucket:string;storage_path:string;arquivo_nome:string;mime_type:string;tamanho_bytes:number;sha256:string};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const safe=(e:unknown)=>String(e instanceof Error?e.message:e??"unknown_error").replace(/[\r\n]+/g," ").slice(0,1000);
const b64u=(b:Uint8Array)=>{let s="";for(let i=0;i<b.length;i+=0x8000)s+=String.fromCharCode(...b.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")};
const sha=async(a:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",a))).map(b=>b.toString(16).padStart(2,"0")).join("");
const shaText=async(s:string)=>sha(new TextEncoder().encode(s).buffer);
async function token(){const id=Deno.env.get("GOOGLE_DRIVE_OAUTH_CLIENT_ID")||"",secret=Deno.env.get("GOOGLE_DRIVE_OAUTH_CLIENT_SECRET")||"",refresh=Deno.env.get("GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN")||"";if(!id||!secret||!refresh)throw new Error("google_oauth_not_configured");const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refresh,grant_type:"refresh_token"})});if(!r.ok)throw new Error("google_oauth_token_failed:"+r.status);const j=await r.json();if(!j.access_token)throw new Error("google_oauth_token_missing");return j.access_token}
const driveQueryValue=(s:string)=>s.replace(/\\/g,"\\\\").replace(/'/g,"\\'");
async function exactChildFolder(t:string,parent:string,name:string,label:string){const q="'"+driveQueryValue(parent)+"' in parents and name = '"+driveQueryValue(name)+"' and mimeType = 'application/vnd.google-apps.folder' and trashed = false";const r=await fetch("https://www.googleapis.com/drive/v3/files?"+new URLSearchParams({q,spaces:"drive",supportsAllDrives:"true",includeItemsFromAllDrives:"true",pageSize:"100",fields:"files(id,name,mimeType,driveId)"}),{headers:{authorization:"Bearer "+t}});if(!r.ok)throw new Error("drive_folder_lookup_failed:"+label+":"+r.status);const fs=(await r.json()).files??[];if(fs.length!==1)throw new Error(fs.length===0?"drive_folder_missing:"+label:"drive_folder_ambiguous:"+label);return String(fs[0].id)}
async function resolvePatrimonioFolder(admin:any,t:string,root:string,patrimonioId:number){const {data:p,error:pe}=await admin.from("patrimonios").select("id,numero_patrimonio,unidade_id").eq("id",patrimonioId).maybeSingle();if(pe||!p)throw new Error("patrimonio_not_found");const {data:u,error:ue}=await admin.from("unidades").select("id,nome").eq("id",p.unidade_id).maybeSingle();if(ue||!u)throw new Error("unidade_not_found");const unit=String(u.nome).trim();const numero=String(p.numero_patrimonio).trim();if(!unit||!numero)throw new Error("patrimonio_routing_data_missing");const unitFolder=await exactChildFolder(t,root,unit,"unidade");return await exactChildFolder(t,unitFolder,"Patrimônio "+numero,"patrimonio")}
async function findDrive(t:string,folder:string,outboxId:number){const q="'"+driveQueryValue(folder)+"' in parents and trashed=false and appProperties has { key='gti_outbox_id' and value='"+outboxId+"' }";const r=await fetch("https://www.googleapis.com/drive/v3/files?"+new URLSearchParams({q,spaces:"drive",supportsAllDrives:"true",includeItemsFromAllDrives:"true",pageSize:"10",fields:"files(id,name,size,mimeType,webViewLink,appProperties)"}),{headers:{authorization:"Bearer "+t}});if(!r.ok)throw new Error("drive_search_failed:"+r.status);return (await r.json()).files?.[0]??null}
function mp(meta:Record<string,unknown>,bytes:ArrayBuffer,mime:string,boundary:string){const e=new TextEncoder(),a=e.encode("--"+boundary+"\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n"+JSON.stringify(meta)+"\r\n--"+boundary+"\r\nContent-Type: "+mime+"\r\n\r\n"),z=e.encode("\r\n--"+boundary+"--\r\n"),o=new Uint8Array(a.length+bytes.byteLength+z.length);o.set(a);o.set(new Uint8Array(bytes),a.length);o.set(z,a.length+bytes.byteLength);return o}
async function upload(t:string,folder:string,name:string,mime:string,bytes:ArrayBuffer,h:string,outboxId:number,fotoId:number,patrimonioId:number){const boundary="gti_"+crypto.randomUUID().replaceAll("-",""),r=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,size,mimeType,webViewLink,appProperties",{method:"POST",headers:{authorization:"Bearer "+t,"content-type":"multipart/related; boundary="+boundary},body:mp({name,parents:[folder],appProperties:{gti_outbox_id:String(outboxId),gti_foto_id:String(fotoId),gti_patrimonio_id:String(patrimonioId),sha256:h}},bytes,mime,boundary)});if(!r.ok)throw new Error("drive_upload_failed:"+r.status+":"+String(await r.text()).slice(0,400));return await r.json()}

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({error:"worker_configuration_missing"},500);
 const admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
 let body:any={};try{body=await req.json()}catch{}
 const mode=body.mode??"dry_run",limit=Math.min(Math.max(Number(body.limit??10)||10,1),MAX_BATCH);
 if(!["dry_run","process","validate_drive"].includes(mode))return json({ok:false,error:"invalid_mode"},400);
 const enabled=Deno.env.get("DRIVE_PROCESSING_ENABLED")==="true",oauthId=Deno.env.get("GOOGLE_DRIVE_OAUTH_CLIENT_ID")||"",oauthSecret=Deno.env.get("GOOGLE_DRIVE_OAUTH_CLIENT_SECRET")||"",refresh=Deno.env.get("GOOGLE_DRIVE_OAUTH_REFRESH_TOKEN")||"",root=Deno.env.get("GOOGLE_DRIVE_FOLDER_ID")||"";
 if(mode==="process"&&(!enabled||!oauthId||!oauthSecret||!refresh||!root))return json({ok:false,error:"drive_processing_not_configured",configuration:{processing_enabled:enabled,oauth_configured:Boolean(oauthId&&oauthSecret&&refresh),destination_configured:Boolean(root)},claimed_changes:0,synced_changes:0},409);
 if(mode==="validate_drive"){
   if(!oauthId||!oauthSecret||!refresh||!root)return json({ok:false,error:"drive_configuration_incomplete",external_write:false},409);
   try{const tk=await token();const r=await fetch("https://www.googleapis.com/drive/v3/files/"+encodeURIComponent(root)+"?supportsAllDrives=true&fields=id,mimeType,driveId,capabilities(canAddChildren,canModifyContent)",{headers:{authorization:"Bearer "+tk}});if(!r.ok)throw new Error("drive_destination_read_failed:"+r.status+":"+safe(await r.text()));const d=await r.json();if(String(d.id||"")!==root||d.mimeType!=="application/vnd.google-apps.folder"||d.capabilities?.canAddChildren!==true||d.capabilities?.canModifyContent!==true)throw new Error("drive_destination_not_writable");const probe=await fetch("https://www.googleapis.com/drive/v3/files?"+new URLSearchParams({q:"'"+driveQueryValue(root)+"' in parents and trashed=false",spaces:"drive",supportsAllDrives:"true",includeItemsFromAllDrives:"true",pageSize:"1",fields:"files(id)"}),{headers:{authorization:"Bearer "+tk}});if(!probe.ok)throw new Error("drive_search_probe_failed:"+probe.status);return json({ok:true,worker:"outbox-drive-worker",mode:"validate_drive",external_write:false,destination_is_folder:true,destination_writable:true,root_routing:"unit_exact_then_patrimonio_exact",shared_drive:Boolean(d.driveId)});}catch(e){return json({ok:false,error:"drive_validation_failed",detail:safe(e),external_write:false},502)}
 }
 if(mode==="dry_run"){const {data:items,error}=await admin.from("patrimonio_fotos_drive_outbox").select("id,patrimonio_id,foto_id,evento,status,tentativas,proxima_tentativa_em").eq("status","pending").order("id",{ascending:true}).limit(limit);if(error)return json({ok:false,error:"outbox_read_failed"},500);const results=[];for(const i of (items??[]) as O[]){const {data:f,error:fe}=await admin.from("patrimonio_fotos").select("id,patrimonio_id,storage_bucket,storage_path,arquivo_nome,mime_type,tamanho_bytes,sha256").eq("id",i.foto_id).maybeSingle();if(fe||!f){results.push({outbox_id:i.id,valid:false,error:fe?"foto_read_failed":"foto_not_found"});continue}const x=f as F;const {data:o,error:se}=await admin.storage.from(BUCKET).download(x.storage_path);if(se||!o){results.push({outbox_id:i.id,valid:false,error:"storage_download_failed"});continue}const bytes=await o.arrayBuffer(),h=await sha(bytes);results.push({outbox_id:i.id,foto_id:i.foto_id,valid:bytes.byteLength===x.tamanho_bytes&&h===String(x.sha256).trim().toLowerCase(),external_write:false})}return json({ok:true,worker:"outbox-drive-worker",mode,external_write:false,claimed_changes:0,synced_changes:0,checked:results.length,results})}
 let tk:string;try{tk=await token()}catch(e){return json({ok:false,error:"google_auth_failed",detail:safe(e),claimed_changes:0,synced_changes:0},502)}
 const {data:claimedItems,error:claimError}=await admin.rpc("claim_patrimonio_fotos_drive_outbox",{p_limit:limit,p_stale_after:"15 minutes"});if(claimError)return json({ok:false,error:"outbox_claim_failed",detail:safe(claimError),claimed_changes:0,synced_changes:0},500);
 let claimed=0,synced=0;const results=[];
 for(const i of (claimedItems??[]) as O[]){claimed++;try{const {data:f,error:fe}=await admin.from("patrimonio_fotos").select("id,patrimonio_id,storage_bucket,storage_path,arquivo_nome,mime_type,tamanho_bytes,sha256").eq("id",i.foto_id).maybeSingle();if(fe||!f)throw new Error("foto_not_found");const x=f as F;if(x.storage_bucket!==BUCKET)throw new Error("unexpected_storage_bucket");const {data:o,error:se}=await admin.storage.from(BUCKET).download(x.storage_path);if(se||!o)throw new Error("storage_download_failed");const bytes=await o.arrayBuffer(),h=await sha(bytes);if(bytes.byteLength!==x.tamanho_bytes||h!==String(x.sha256).trim().toLowerCase())throw new Error("storage_integrity_mismatch");const targetFolder=await resolvePatrimonioFolder(admin,tk,root,x.patrimonio_id);let d=await findDrive(tk,targetFolder,i.id);if(!d)d=await upload(tk,targetFolder,x.arquivo_nome||("foto-"+x.id+".jpg"),x.mime_type,bytes,h,i.id,x.id,x.patrimonio_id);if(!d?.id)throw new Error("drive_file_id_missing");if(String(d.appProperties?.gti_outbox_id||"")!==String(i.id)||String(d.appProperties?.gti_foto_id||"")!==String(x.id)||String(d.appProperties?.sha256||"").toLowerCase()!==h||Number(d.size||-1)!==bytes.byteLength)throw new Error("drive_identity_or_integrity_mismatch");const web=String(d.webViewLink||("https://drive.google.com/open?id="+d.id));const {data:fin,error:fe2}=await admin.rpc("finalize_patrimonio_fotos_drive_outbox",{p_outbox_id:i.id,p_drive_file_id:String(d.id),p_drive_file_name:String(d.name||x.arquivo_nome||("foto-"+x.id+".jpg")),p_drive_folder_id:targetFolder,p_drive_web_url:web,p_drive_sha256:h});if(fe2)throw new Error("outbox_finalize_failed");synced++;results.push({outbox_id:i.id,foto_id:i.foto_id,status:"synced",drive_file_id:String(d.id),drive_folder_id:targetFolder,sha256:h,finalize:fin})}catch(e){const msg=safe(e);const {error:fe}=await admin.rpc("fail_patrimonio_fotos_drive_outbox",{p_outbox_id:i.id,p_error:msg,p_retry_after:"5 minutes",p_max_attempts:MAX_ATTEMPTS});results.push({outbox_id:i.id,foto_id:i.foto_id,status:"failed",error:msg,fail_recorded:!fe})}}
 return json({ok:true,worker:"outbox-drive-worker",mode:"process",external_write:true,claimed_changes:claimed,synced_changes:synced,checked:results.length,results});
});