CREATE TABLE public.movimentacoes_patrimonio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patrimonio_id bigint NOT NULL,
  tipo varchar(20) NOT NULL CHECK (tipo IN ('ENTRADA','SAIDA','TRANSFERENCIA')),
  unidade_origem_id bigint NULL,
  setor_origem_id bigint NULL,
  unidade_destino_id bigint NULL,
  setor_destino_id bigint NULL,
  motivo varchar(100) NULL,
  observacao varchar(500) NULL,
  usuario varchar(255) NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_mov_patrimonio
    FOREIGN KEY (patrimonio_id) REFERENCES public.patrimonios(id) ON DELETE RESTRICT,
  CONSTRAINT fk_mov_unidade_origem
    FOREIGN KEY (unidade_origem_id) REFERENCES public.unidades(id) ON DELETE RESTRICT,
  CONSTRAINT fk_mov_setor_origem
    FOREIGN KEY (setor_origem_id) REFERENCES public.setores(id) ON DELETE RESTRICT,
  CONSTRAINT fk_mov_unidade_destino
    FOREIGN KEY (unidade_destino_id) REFERENCES public.unidades(id) ON DELETE RESTRICT,
  CONSTRAINT fk_mov_setor_destino
    FOREIGN KEY (setor_destino_id) REFERENCES public.setores(id) ON DELETE RESTRICT,
  CONSTRAINT ck_mov_origem_setor
    CHECK (setor_origem_id IS NULL OR unidade_origem_id IS NOT NULL),
  CONSTRAINT ck_mov_destino_setor
    CHECK (setor_destino_id IS NULL OR unidade_destino_id IS NOT NULL)
);

CREATE INDEX idx_mov_patrimonio_criado
  ON public.movimentacoes_patrimonio (patrimonio_id, criado_em DESC);

CREATE INDEX idx_mov_unidade_origem
  ON public.movimentacoes_patrimonio (unidade_origem_id);

CREATE INDEX idx_mov_unidade_destino
  ON public.movimentacoes_patrimonio (unidade_destino_id);

ALTER TABLE public.movimentacoes_patrimonio ENABLE ROW LEVEL SECURITY;
